name: Build Binaries

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    name: Build binaries
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '^1.24'

      - name: Build
        run: |
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} \
          go build -o moosic-decoder-${{ matrix.goos }}-${{ matrix.goarch }} main.go

      - name: Upload binary to release
        uses: softprops/action-gh-release@v1
        with:
          name: moosic-decoder-${{ matrix.goos }}-${{ matrix.goarch }}
          tag_name: ${{ github.ref_name }}
          files: moosic-decoder-${{ matrix.goos }}-${{ matrix.goarch }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
